Aladdin
AladdinOmar61/dummy-blog-server pull request #6
Opened 2023-04-06 21:17 UTC by AladdinOmar61

2023-04-07 12:17 UTC, diabeatz96 commented on frontend/coolblogs/src/routes/Home.jsx
Do not return twice,  Please put the Header and Footer Component inside of one return Statement

2023-04-07 12:18 UTC, diabeatz96 commented on frontend/coolblogs/src/routes/Home.jsx
Please change outer div tag to "main" tag for semantic elements

2023-04-07 12:19 UTC, diabeatz96 commented on frontend/coolblogs/src/components/Header.jsx
Please add an outer <nav> </nav> tag for semantic element handling.

2023-04-07 12:26 UTC, diabeatz96 commented on frontend/coolblogs/src/routes/SingleBlog.jsx
> +    getSingleBlogPost();
you need to pass in the postId in reducer, 

for example you have to pass in parameter thisn way:
parameter = (postId, title, content) order matters, if you don't need a parameter, pass in null,

So now you have to actually get the post id, so how do you get the postid? You use useParams() or whatever the function is to get the current number we are on in the url,

postId = some use paramsParams function while cutting the string to get just the number from it.
  `const { state, getSingleBlogPost } = useGlobalReducer(postId);`

2023-04-07 12:26 UTC, diabeatz96 commented on frontend/coolblogs/src/routes/SingleBlog.jsx
Make out div tag a "section"

2023-04-07 12:27 UTC, diabeatz96 commented on frontend/coolblogs/src/utils/useGlobalReducer.jsx
remove console.log in push

2023-04-07 12:27 UTC, diabeatz96 requested changes
I added an Array of comments to improve code and make it better.

2023-04-09 19:29 UTC, AladdinOmar61 commented on frontend/coolblogs/src/routes/Home.jsx
I believe there are two return statements there because one of them is for the mapping function. If I remove the inner return I get syntax errors.

2023-04-09 19:44 UTC, AladdinOmar61 commented on frontend/coolblogs/src/utils/useGlobalReducer.jsx
I get syntax errors when I remove `console.log(error)` in any of the functions. Replacing them with `return error` does not work either. Any suggestions?

2023-04-10 12:12 UTC, merged